### ISSUE TITLE
lstat

### ISSUE THREAD

**Issue by voipllc** [zackelia/ghidra-dark#37]
Traceback (most recent call last):
  File "/mnt/c/Users/avoid/Downloads/ghidra-dark/install.py", line 207, in <module>
    main(parser.parse_args())
  File "/mnt/c/Users/avoid/Downloads/ghidra-dark/install.py", line 170, in main
    ghidra_install_path = get_ghidra_install_path(args.install_path)
  File "/mnt/c/Users/avoid/Downloads/ghidra-dark/install.py", line 54, in get_ghidra_install_path
    if os.path.islink(ghidra_symlink_path):
  File "/usr/lib/python3.10/posixpath.py", line 167, in islink
    st = os.lstat(path)
TypeError: lstat: path should be string, bytes or os.PathLike, not NoneType

**Comment by voipllc** [comment]
C:\Users\avoid\Downloads\ghidra-dark>python3 install.py
Traceback (most recent call last):
  File "C:\Users\avoid\Downloads\ghidra-dark\install.py", line 207, in <module>
    main(parser.parse_args())
  File "C:\Users\avoid\Downloads\ghidra-dark\install.py", line 170, in main
    ghidra_install_path = get_ghidra_install_path(args.install_path)
  File "C:\Users\avoid\Downloads\ghidra-dark\install.py", line 54, in get_ghidra_install_path
    if os.path.islink(ghidra_symlink_path):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 259, in islink
    st = os.lstat(path)
TypeError: lstat: path should be string, bytes or os.PathLike, not NoneType

C:\Users\avoid\Downloads\ghidra-dark>

heres command prompt

**Comment by IppSec** [comment]
Set your path to include the directory ghidraRun is stored then try it again.

**Comment by zackelia** [comment]
Sorry about that, I clearly didn't fully test a recent change, but this error is fixed in 066e4e1. As @IppSec mentioned, you need `--path`, but ghidra-dark should tell you this now that it is fixed.
